find /v /c ""  Alerts_MOD.bas
find /v /c ""  Array_MOD.bas
find /v /c ""  a_Dahl_MOD.bas
find /v /c ""  A_Globals_MOD.bas
find /v /c ""  a__A_MOD.bas
find /v /c ""  A__Text_MOD.bas
find /v /c ""  Box_MOD.bas
find /v /c ""  Callbacks_MOD.bas
find /v /c ""  Clipboard_MOD.bas
find /v /c ""  CollapseApt_MOD.bas
find /v /c ""  ColorUtils_MOD.bas
find /v /c ""  ColumnUtils_MOD.bas
find /v /c ""  Comment_MOD.bas
find /v /c ""  ConvertUTC_Mod.bas
find /v /c ""  CountOf_MOD.bas
find /v /c ""  DailyProcessing_MOD.bas
find /v /c ""  DatabaseAccess_MOD.bas
find /v /c ""  DBConnect_MOD.bas
find /v /c ""  DBCreateTable_MOD.bas
find /v /c ""  DBDrillDown_MOD.bas
find /v /c ""  DBInsert_MOD.bas
find /v /c ""  DBQuery2_MOD.bas
find /v /c ""  DBQueryBuilder_MOD.bas
find /v /c ""  DBQuery_MOD.bas
find /v /c ""  DBUpdate_MOD.bas
find /v /c ""  Decile_MOD.bas
find /v /c ""  Deploy_MOD.bas
find /v /c ""  Display_MOD.bas
find /v /c ""  DoEvents_MOD.bas
find /v /c ""  Drilldown_MOD.bas
find /v /c ""  Duplicates_MOD.bas
find /v /c ""  Fastload_MOD.bas
find /v /c ""  FieldsForm_MOD.bas
find /v /c ""  File_MOD.bas
find /v /c ""  Filter_MOD.bas
find /v /c ""  FindUtils_MOD.bas
find /v /c ""  Find_MOD.bas
find /v /c ""  Format_MOD.bas
find /v /c ""  GetValues_MOD.bas
find /v /c ""  Goto_MOD.bas
find /v /c ""  Highlight_MOD.bas
find /v /c ""  Identify_MOD.bas
find /v /c ""  LG_mod.bas
find /v /c ""  Lookup_MOD.bas
find /v /c ""  Markie_MOD.bas
find /v /c ""  MatchRowIndex_MOD.bas
find /v /c ""  mDisconnected_MOD.bas
find /v /c ""  Misc_MOD.bas
find /v /c ""  mMeterLookBack_MOD.bas
find /v /c ""  mProximity_MOD.bas
find /v /c ""  NoDups_MOD.bas
find /v /c ""  Parse_MOD.bas
find /v /c ""  Phase_MOD.bas
find /v /c ""  Pivot_MOD.bas
find /v /c ""  PowerOn_MOD.bas
find /v /c ""  ProgressBar_MOD.bas
find /v /c ""  ProgressMeter_MOD.bas
find /v /c ""  ProximityGraph_MOD.bas
find /v /c ""  QueryAnalyst_MOD.bas
find /v /c ""  QueryParser_MOD.bas
find /v /c ""  Range_MOD.bas
find /v /c ""  Recordset_MOD.bas
find /v /c ""  Ribbon_MOD.bas
find /v /c ""  RowsUtils_MOD.bas
find /v /c ""  SaveModule_MOD.bas
find /v /c ""  ScratchLib_MOD.bas
find /v /c ""  SheetLib_MOD.bas
find /v /c ""  ShellAndWait_MOD.bas
find /v /c ""  ShellRun_MOD.bas
find /v /c ""  ShowDetail_MOD.bas
find /v /c ""  Show_MOD.bas
find /v /c ""  Singletons_MOD.bas
find /v /c ""  Sort_MOD.bas
find /v /c ""  Split_MOD.bas
find /v /c ""  SQLParser_MOD.bas
find /v /c ""  SSNMeterStatus_MOD.bas
find /v /c ""  SSNUpload_MOD.bas
find /v /c ""  SSN_MOD.bas
find /v /c ""  Strings_MOD.bas
find /v /c ""  SystemCall_MOD.bas
find /v /c ""  TableMap_MOD.bas
find /v /c ""  TableUtils_MOD.bas
find /v /c ""  Teradata_MOD.bas
find /v /c ""  Timer_MOD.bas
find /v /c ""  TPT_MOD.bas
find /v /c ""  UnderVoltage_MOD.bas
find /v /c ""  UsageTracker_MOD.bas
find /v /c ""  Utillib_MOD.bas
find /v /c ""  VKWH_MOD.bas
find /v /c ""  VlookupSheetMerge_MOD.bas
find /v /c ""  Vlookup_MOD.bas
find /v /c ""  ZipCodeColumn_MOD.bas
